version: '3.8'

services:
  node-app:
    # image: node-app:latest
    image: kasugaiyuta19980519/test-nodeapp:nodeimage
    ports: 
      - "4000:4000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=4000
    depends_on:
      - node-mysql
    tty: true
    # env_file:
    #   - ./.env
  
  node-mysql:
    # image: node-mysql:latest
    image: kasugaiyuta19980519/test-mysql:mysqlimage
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_USER=yuta
      - MYSQL_PASSWORD=secret_pass!123
      - MYSQL_ROOT_PASSWORD=secret_pass!123
      - MYSQL_DATABASE=mysql_dockerdb

networks:
  default:
    driver: bridge
    ipam: 
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1