version: '3.8'

services:
  node-app:
    build: .
    ports: 
      - "4000:4000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=4000
    depends_on:
      - node-mysql
    # env_file:
    #   - ./.env
  
  node-mysql:
    image: mysql:latest
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_USER=yuta
      - MYSQL_PASSWORD=secret_pass!123
      - MYSQL_ROOT_PASSWORD=secret_pass!123
      - MYSQL_DATABASE=mysql_dockerdb
  
    
